export enum AppInjectors {
  MICRO_SERVICE__IMAGE_PROCESSOR = 'MICRO_SERVICE__IMAGE_PROCESSOR',
  SERVICE__JOI = 'SERVICE__JOI',

  OPTIONS__SENTRY = 'OPTIONS__SENTRY',
  OPTIONS__IMAGE = "OPTIONS__IMAGE",
}
